config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :items do 
    resources :bids, only: [:create]
  end

  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :maximum_bid, numericality: { greater_than: :amount }, allow_nil: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :seller, class_name: 'User'
  has_many :bids, dependent: :destroy

  validates :title, :description, :starting_price, :minimum_selling_price, :start_time, :end_time, presence: true
  validates :starting_price, :minimum_selling_price, numericality: { greater_than_or_equal_to: 0 }
  validate :msp_greater_than_starting_price

  after_create :schedule_auction_end

  private

  def msp_greater_than_starting_price
    if minimum_selling_price.present? && starting_price.present? && minimum_selling_price < starting_price
      errors.add(:minimum_selling_price, "must be greater than or equal to the starting price")
    end
  end

  def schedule_auction_end
    EndAuctionJob.set(wait_until: end_time).perform_later(id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, foreign_key: 'seller_id', dependent: :destroy
  has_many :bids, dependent: :destroy

  enum role: {
    seller: 0,
    buyer: 1
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    attributes = [:role]
    params[:user][:role] = params[:user][:role].to_i if params[:user]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!

  def create
    @item = Item.find(params[:item_id])
    @bid = @item.bids.build(bid_params)
    @bid.user = current_user
    BidService.new(@item,@bid).place_bid

    if @bid.save!
      redirect_to @item, notice: 'Your bid was placed successfully.'
    else
      redirect_to @item, alert: 'Failed to place bid.'
    end
  end

  private

  def bid_params
    params.require(:bid).permit(:amount, :maximum_bid)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_items, only: [:show, :edit, :update, :destroy]


  def index
    @items = Item.all
  end

  def show
    @bids = @item.bids.order(amount: :desc)
  end

  def new
    @item = current_user.items.build
  end
  
  def create
    @item = current_user.items.build(item_params)
    if @item.save!
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated. '
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed. '
  end

  private

  def set_items
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :starting_price, :minimum_selling_price, :start_time, :end_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/bids/_bid.html.erb
<li><%= bid.user.email %>: <%= bid.amount %></li>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :starting_price %>
    <%= form.number_field :starting_price %>
  </div>

  <div class="field">
    <%= form.label :minimum_selling_price %>
    <%= form.number_field :minimum_selling_price %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form', item: @item %>
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Items for Auction</h1>

<% if user_signed_in? %>
  <%= link_to 'New Item', new_item_path, class: "btn btn-primary" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Starting Price</th>
      <th>Minimum Selling Price</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= truncate(item.description, length: 50) %></td>
        <td><%= number_to_currency(item.starting_price) %></td>
        <td><%= number_to_currency(item.minimum_selling_price) %></td>
        <td><%= item.start_time.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td><%= item.end_time.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td><%= link_to 'View Item', item_path(item), class: "btn btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>
<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Starting Price:</strong>
  <%= @item.starting_price %>
</p>

<p>
  <strong>Minimum Selling Price:</strong>
  <%= @item.minimum_selling_price %>
</p>

<p>
  <strong>Current Highest Bid:</strong>
  <%= @item.bids.maximum(:amount) %>
</p>

<p>
  <strong>Auction End Time:</strong>
  <%= @item.end_time %>
</p>

<% if @item.winner_id.present? %>
<p><strong>Winner:</strong> <%= User.find(@item.winner_id).email %></p>
<% end %>

<h2>Bids</h2>
<% if current_user.buyer? %>
  <% if user_signed_in? %>
    <%= form_with(model: [ @item, @item.bids.build ], local: true) do |form| %>
      <div class="field">
        <%= form.label :amount %>
        <%= form.number_field :amount %>
      </div>

      <div class="field">
        <%= form.label :maximum_bid %>
        <%= form.number_field :maximum_bid %>
      </div>

      <div class="actions">
        <%= form.submit 'Place Bid' %>
      </div>
    <% end %>
  <% else %>
    <p>You must <%= link_to 'sign in', new_user_session_path %> to place a bid.</p>
  <% end %>
<% end %> 

<% if current_user.seller? %>
<h3>Current Bids</h3>
<div id="bids" data-item-id="<%= @item.id %>">
  <ul id="bids-list">
    <% @bids.each do |bid| %>
      <%= render bid %>
    <% end %>
  </ul>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuctionSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>